### ISSUE TITLE
Crashes on PSP Go

### ISSUE THREAD

**Issue by yeenoffthebone** [bucanero/pkgi-psp#10]
It gets struck on logo and flashes all leds then shut downs.

**Comment by bucanero** [comment]
The app has been tested on PSP Go with no issues.

So you need to provide full details, like:
- firmware version / CFW version
- additional plugins
- mem-stick or internal memory?
- install path

**Comment by yeenoffthebone** [comment]
Software: 6.61 pro-c
Plugins: Cwcheat, category lite, cxmb, cwcheat, nploader_mod, npdrm_free_mod, cwcheatpops, nploader_mods, npdrm_free_mod.
Storage: Internal storage
Path: PSP GO (F:)/PSP/PKGI

**Comment by bucanero** [comment]
I don't have a PSP Go, but I know it works fine on PSP Go. As reference here's a video found on youtube: https://www.youtube.com/watch?v=E4bfkp4OoCM

I suggest disabling all plugins, and try to start the app. Also it should be installed to `/PSP/GAME/PKGI`

**Comment by G00dYDK** [comment]
I had the same problem, then I disabled the npdrm_free_mod plugins, and then it worked

**Comment by yeenoffthebone** [comment]
Yea only worked when I disabled all plugins
