### ISSUE TITLE
Crash When Searching

### ISSUE THREAD

**Issue by TravisDecker** [bucanero/pkgi-psp#16]
I get a full system crash when I start pkgi-psp and start a search right away( within a few seconds of the menu starting).It appears that pkgi-psp freezes, and when I attempt to go home it i get the "do you want to quit the game", I select yes and it stalls on the Grey "please wait" and eventually powers off. If I wait a while, and scroll up and down in the initial game list, it seems to prevent the issue. That said, I did run into the bug when refining a search as well
Details - 
PSP 3001 (North America) 
Firmware PRO-C 6.61 
Pkgi-psp v1.0.0

**Comment by TravisDecker** [comment]
Crash when searching I get a full system crash when I start pkgi-psp and start a search right away( within a few seconds of the menu starting).It appears that pkgi-psp freezes, and when I attempt to go home it i get the "do you want to quit the game", I select yes and it stalls on the Grey "please wait" and eventually powers off. If I wait a while, and scroll up and down in the initial game list, it seems to prevent the issue. That said, I did run into the bug when refining a search as well

**Comment by bucanero** [comment]
just in case, could you test this new build, that reduced the memory requirement during dialogs?
https://www.mediafire.com/file/qhmj8rht3yvx3cp/pkgi-psp.zip/file

(not sure if it could have any impact with this issue)

**Comment by TravisDecker** [comment]
It does appear the issue has been resolved.

**Comment by TravisDecker** [comment]
Nice work, keep it up!
