### ISSUE TITLE
.TSV files

### ISSUE THREAD

**Issue by eighthdayregret** [bucanero/pkgi-psp#23]
Any plans on adding support for .TSV files, in order to take advantage of the already existing NPS database?

**Comment by bucanero** [comment]
the app already supports any kind of custom .txt database file format. If you are not using the default .csv format, you should create a `dbformat.txt` configuration file so the app can parse your file. Check notes here:
https://github.com/bucanero/pkgi-psp?tab=readme-ov-file#db-formats

**Comment by eighthdayregret** [comment]
Thank you for the response, I see that in the instructions, however, let me clarify:
I do not see .TSV listed as a usable filetype, so in order to update the database, even after setting custom DB options, would that require changing the file extension?
The reason I ask is because allowing .TSV files would allow for easier updating of the DBs, instead of having to re-download them from NoPaystation and renaming them.

**Comment by bucanero** [comment]
No, file names and extension are mandatory, so a file has to be named `pkgi.txt`, or `pkgi_games.txt`, etc

I can't give any support to specific sites or files, you might want to contact them directly.

**Comment by eighthdayregret** [comment]
Ah, okay. Thanks again for the reply.

**Comment by BrownNPC** [comment]
Just convert tsv to csv and change the file extension to .txt
