### ISSUE TITLE
Themes are downloaded, but don't show up in  the themes folder

### ISSUE THREAD

**Issue by chasemc215** [bucanero/pkgi-psp#8]
I downloaded some themes from the app, and they said that they were downloaded, but once I checked the themes folder, they are nowhere to be seen. -+*Where do the themes go when they are done downloading??

**Comment by BasitAli-12** [comment]
Same issue, Please fix it!

**Comment by bucanero** [comment]
themes are a specific type of .pkg that is not currently supported. Decrypting and installing this type of pkg will be added to a new release.
